MEANS = ["0", "1", "2" ]
SIGMAS = ["1", "2" ]

rule all:
   input:
      expand("summary_mu={mean}_sigma={sigma}.toml", mean=MEANS, sigma=SIGMAS)

rule instantiate:
   output: 
      "0_instantiated"
   shell:
      "julia --project -e 'import Pkg; Pkg.instantiate()'; touch {output}"

rule gen_rand_vars:
   input:
      check = "0_instantiated"
   params:
      num_draws = "10"
   output:
      "draws_mu={mean}_sigma={sigma}.csv"
   shell:
      "julia --project draw_vars.jl --mean={wildcards.mean} --sigma={wildcards.sigma} --n={params.num_draws} {output}"

rule calc_summary:
   input:
      check = "0_instantiated",
      fn = "draws_mu={mean}_sigma={sigma}.csv"
   output:
      "summary_mu={mean}_sigma={sigma}.toml"
   shell:
      "julia --project calc_summary.jl {input.fn} > {output} "


