fits_dir: input
toml_dir: output
csv_dir:  output
out_dir:  output

download_script: neid_download_files_2023_10_14.sh

preprocess_param: 1.0

#slurm_account: ebf11-fa23
slurm_account: open
slurm_partition: open
