DATETIMES, = glob_wildcards("neidL2_{datetime}.fits")

rule all:
   input:
      "0_instantiated",
      "0_download_complete",
      expand("neidL2_{datetime}.toml", datetime=DATETIMES),
      "output.csv"

rule instantiate:
   output: 
      "0_instantiated"
   shell:
      "julia --project -e 'import Pkg; Pkg.instantiate()'; touch {output}"

rule download:
   output: 
      "0_download_complete" 
   shell:
      "source neid_download_files_2023_10_14.sh; touch {output}"

rule make_toml:
   input:
      fits = "neidL2_{datetime}.fits",
      check1 = "0_instantiated",
      check2 = "0_download_complete" 
   output:
      "neidL2_{datetime}.toml"
   shell:
      "julia --project preprocess.jl {input.fits} {output} "

rule post_process:
   input:
      check1 = "0_instantiated",
      check2 = "0_download_complete", 
      input_fn = expand("neidL2_{datetime}.toml", datetime=DATETIMES)
   output:
      "output.csv"
   shell:
      "julia --project postprocess.jl . {output}"

