default-resources: 
   mem_mb_per_cpu: 4096
   nodes: 1  
   tasks: 1
   cpus_per_task: 1
   runtime: 15   
cluster: "sbatch --job-name={rule} -A open --partition open --time={resources.runtime} --nodes={resources.nodes} --ntasks={resources.tasks} --cpus-per-task={resources.cpus_per_task} --mem-per-cpu={resources.mem_mb_per_cpu} --export=ALL"
jobs: 90
verbose: true
notemp: true
